"use strict";
exports.CREATE_BOARD = 'CREATE_BOARD';
exports.CREATE_BOARD_SUCCESS = 'CREATE_BOARD_SUCCESS';
exports.BOARD_LIST_REQUEST = 'BOARD_LIST_REQUEST';
exports.BOARD_LIST_SUCCESS = 'BOARD_LIST_SUCCESS';
exports.LOAD_BOARD = 'LOAD_BOARD';
exports.LOAD_BOARD_SUCCESS = 'LOAD_BOARD_SUCCESS';
exports.MODIFY_BOARD = 'MODIFY_BOARD';
exports.MODIFY_BOARD_SUCCESS = 'MODIFY_BOARD_SUCCESS';
exports.CREATE_LIST_REQUEST = 'CREATE_LIST_REQUEST';
exports.CREATE_LIST_REQUEST_SUCCESS = 'CREATE_LIST_REQUEST_SUCCESS';
//# sourceMappingURL=board_action_enum.js.map