"use strict";
exports.CREATE_BOARD = 'CREATE_BOARD';
exports.CREATE_BOARD_SUCCESS = 'CREATE_BOARD_SUCCESS';
exports.LOAD_BOARD_LIST = 'LOAD_BOARD_LIST';
exports.LOAD_BOARD_LIST_SUCCESS = 'LOAD_BOARD_LIST_SUCCESS';
exports.LOAD_BOARD = 'LOAD_BOARD';
exports.LOAD_BOARD_SUCCESS = 'LOAD_BOARD_SUCCESS';
exports.MODIFY_BOARD = 'MODIFY_BOARD';
exports.MODIFY_BOARD_SUCCESS = 'MODIFY_BOARD_SUCCESS';
//# sourceMappingURL=board_action_enum.js.map