export const CREATE_BOARD = 'CREATE_BOARD';
export const CREATE_BOARD_SUCCESS = 'CREATE_BOARD_SUCCESS';
export const LOAD_BOARD_LIST = 'LOAD_BOARD_LIST';
export const LOAD_BOARD_LIST_SUCCESS = 'LOAD_BOARD_LIST_SUCCESS';
export const LOAD_BOARD = 'LOAD_BOARD';
export const LOAD_BOARD_SUCCESS = 'LOAD_BOARD_SUCCESS';
